### ISSUE TITLE
[Win] KeyError: 'width'

### ISSUE THREAD

**Issue by biggestsonicfan** [JumpJets/boosty_archiver#1]
The logs from `boosty_archiver` are quite verbose, and the stylization doesn't make it too much easier to condense into a log.

There's a bit of cookie and token data spilled into the logs that I have mostly redacted, but aside from being a log from paywalled content, I have taken the precaution to password zip the log anyway to avoid scraping. The password is simply `ytsoob`
[error.zip](https://github.com/user-attachments/files/17215279/error.zip)

**Comment by XCanG** [comment]
I see, I found out in log that default image to post, that you have https://images.boosty.to/image/69a5ee03-b9c8-4e53-acfb-163b510443c0 point out to default asset https://images.boosty.to/stubs/default.png
It may be deleted or something like that, because of that it does not have width, height and size.

I can solve it into either **a)** check for fields and skip or **b)** grab fields with fallback.
The first solution would stop from downloading `default.png`s which is better, but if for some reason there is actual image in the API that it can't determine dimensions, say, svg, then this would be not ideal solution.

**Comment by XCanG** [comment]
Also if width and height are relatively not important, I still use size to check if I should redownload file if file is present and DB is not used. (for a cases like partial download - it will redownload)

So if I will use fallback solution this will not be ideal as I would need to somehow compare files.

**Comment by XCanG** [comment]
I've added fix, check if it solve the issue.

----

Also I added logging for unsupported data types, like of `"video"`. Since I don't have any subscription that have posted video I have to ask you to try to run script against that creator and see in logs when a message popup. You will see red text that says: `Unsupported data type: [type]` and dumped example below. If videos aren't posted as files I would need an example. If it happens, then please create another issue specifically for video type of posts.
